import "./domEnvironment.js";
import { runAllTests } from "./harness.js";
// Import only tests that do not rely on JSON module loading in Node. These specs use inline scenarios.
import "./UnitSystem.rules.test.js";
import "./UnitDamageMatrix.test.js";
import "./HexMapRenderer.animateUnitMove.test.js";
import "./HexMapRenderer.artilleryTargetFx.test.js";
import "./HexMapRenderer.focusOnHex.test.js";
import "./HexMapRenderer.muzzleFlash.test.js";
import "./HexMapRenderer.wreckSilhouette.test.js";
import "./HexMapRenderer.tacticalOverlays.test.js";
import "./HexMapRenderer.engineerFieldworks.test.js";
import "./WreckFxRenderer.test.js";
import "./RoadOverlayRenderer.test.js";
import "./ProceduralPrimitives.test.js";
import "./Combat.directionalFortifications.test.js";
import "./FrameSequenceAnimator.playback.test.js";
import "./SpriteSheetAnimator.layout.test.js";
import "./MapViewport.interactions.test.js";
import "./BattleScreen.animations.test.js";
import "./BattleScreen.airMissionPlayback.test.js";
import "./BattleScreen.activityLog.test.js";
import "./BattleScreen.attackPreview.test.js";
import "./BattleScreen.turnAdvance.test.js";
import "./BattleScreen.selectionIntel.test.js";
import "./BattleScreen.objectiveMarkers.test.js";
import "./BattleScreen.missionFlow.test.js";
import "./AirShow.productionCapture.test.js";
import "./AirShow.speedModel.test.js";
import "./AirShow.bomberSpeed.validation.test.js";
import "./FacingDirection.migration.test.js";
import "./SelectionIntelOverlay.commandCards.test.js";
import "./TutorialOverlay.multiTarget.test.js";
import "./SidebarMiniTutorials.test.js";
import "./unitSpriteCatalog.test.js";
import "./deploymentZonePlanner.test.js";
import "./scenarioValidation.test.js";
import "./CampaignMapRenderer.render.test.js";
import "./CampaignState.observe.test.js";
import "./CampaignScreen.status.test.js";
import "./MissionRules.riverWatch.test.js";
import "./MissionRules.townDefense.test.js";
import "./unlockPurchases.test.js";
// Air Support system tests
import "./AirMissions.arrivals.test.js";
import "./AirInterception.parity.test.js";
import "./AirInterception.layered.test.js";
import "./AirInterception.radius.test.js";
import "./AirStrike.damageRounding.test.js";
import "./AirSupport.summary.test.js";
import "./BotAirHeuristic.test.js";
import "./GroundLogistics.enforcement.test.js";
import "./BattleWarRoomDataProvider.damage.test.js";
import "./EngineerFieldworks.turnConsumption.test.js";
import "./InfantryActions.commandState.test.js";
import "./ArtillerySupport.commandState.test.js";
import "./BotMovement.zeroFuelSupport.test.js";
import "./ReconLOS.directFire.test.js";
import "./ReconBike.balance.test.js";
import "./InfantryTankAssault.autoflank.test.js";
import "./ATGun.combatMath.test.js";
import "./BotTargeting.heuristic.test.js";
import "./precombatLogisticsMinimum.test.js";
import "./AirShow.fighterMotion.test.js";
// Execute the registered tests sequentially.
(async () => {
    await runAllTests();
})();
